### ISSUE TITLE
:bug: Documentation Not Accessible at Root URL `/`, Only Available at `/docs/`

### ISSUE THREAD

**Issue by D-Mielewczyk** [bot-wheels/docs#47]
- Visiting `https://bot-wheels.github.io/` does not display the documentation.
- The documentation loads correctly when accessing `https://bot-wheels.github.io/docs/`.
- This could confuse users who expect the documentation at the root URL.
- **Proposal:** Implement a redirect from `/` to `/docs/` or configure the site to serve the documentation at the root URL.

**Comment by D-Mielewczyk** [comment]
Won't fix @Mihaau please explain why

**Comment by Mihaau** [comment]
To use the root website repo has to be named after it.
